import MainLayout from "@/components/MainLayout/MainLayout";
import "./globals.css";

export const metadata = {
  title: "Travel-guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#f1f5eb]">
       <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
